console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'
version = 3

[palette]
  gold = '#F6C177'
  iris = '#C4A7E7'
  love = '#EB6F92'
  muted = '#6E6A86'
  pine = '#31748F'
  rose = '#EBBCBA'
  subtle = '#908CAA'
  text = '#E0DEF4'

[transient_prompt]
  template = '❯'
  foreground = 'p:iris'
  foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[block.segments]]
    template = ' {{ if .Venv }}({{ .Venv }}){{ end }} '
    foreground = 'p:text'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [block.segments.properties]
      display_mode = 'environment'
      fetch_virtual_env = true
      home_enabled = true

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = 'p:love'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pine'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
     style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<p:iris>*</>{{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} '
    foreground = 'p:subtle'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
       branch_ahead_icon = '<p:subtle>\u21e1 </>'
       branch_behind_icon = '<p:subtle>\u21e3 </>'
       branch_icon = ''
       fetch_stash_count = true
       fetch_status = true
       fetch_upstream_icon = true
       git_icon = ''
       github_icon = ''

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = 'p:gold'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
     style = 'austin'

[[blocks]]
 type = 'prompt'
 alignment = 'left'
 newline = true

 [[blocks.segments]]
   template = '❯ '
   foreground = 'p:iris'
   type = 'status'
   style = 'plain'
   foreground_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']

   [blocks.segments.properties]
    always_enabled = true
